name: ecg_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip:
      - ultralytics
