name: ecg_env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - opencv
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - ultralytics