[tool.poetry]
name = "ecg-digitization-tool"
version = "0.0.1"
description = "This is a project for digitizing electrocardiograms using Python and machine learning."
authors = ["Luan Rodrigues Jorge Amaral"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.4.1"
pandas = "^2.3.3"
matplotlib = "^3.10.8"
scipy = "^1.17.0"
opencv-python = "^4.13.0.90"
pillow = "^12.1.0"
pytesseract = "^0.3.13"
boto3 = "^1.42.30"
scikit-image = "^0.26.0"
ocrd-fork-pylsd = "^0.0.8"
nbconvert = "^7.17.0"
botocore = {extras = ["crt"], version = "^1.42.61"}
python-dotenv = "^1.2.2"
pre-commit = "^4.5.1"
nbstripout = "^0.9.1"
streamlit = "^1.41.0"
ultralytics = "^8.3.0"
pyngrok = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)"
]
