[tool.poetry]
name = "ecg-digitization-tool"
version = "0.0.1"
description = "This is a project for digitizing electrocardiograms using Python and machine learning."
authors = ["Luan Rodrigues Jorge Amaral"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.4.1"
pandas = "^2.3.3"
matplotlib = "^3.10.8"
scipy = "^1.17.0"
opencv-python = "^4.13.0.90"
pillow = "^12.1.0"
pytesseract = "^0.3.13"
boto3 = "^1.42.30"
scikit-image = "^0.26.0"
torch = [
  {url = "https://download.pytorch.org/whl/rocm6.0/torch-2.3.1%2Brocm6.0-cp312-cp312-linux_x86_64.whl", markers = "sys_platform == 'linux'"}
]
torchvision = [
    {url = "https://download.pytorch.org/whl/rocm6.0/torchvision-0.18.1%2Brocm6.0-cp312-cp312-linux_x86_64.whl", markers = "sys_platform == 'linux'"}
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"